Introducing the repository secret
docker-mailserver/docker-mailserver-new pull request #18
Opened 2021-01-17 20:32 UTC by aendeavor

Fixes #17

2021-01-17 20:34 UTC, aendeavor commented
Please note the line in the Dockerfile

``` DOCKERFILE
RUN su - amavis -c "razor-admin -create && sleep 3 && razor-admin -register"
```

Since we're seeing a weird error that sometimes this fails, maybe a short sleep can help here.

2021-01-18 00:08 UTC, radicand requested changes

2021-01-18 00:08 UTC, radicand commented on .github/workflows/default_on_push.yml
> +          tags: ${{ secrets.DOCKER_REPOSITORY }}:ci
Here and below, shouldn't this remain as `mailserver-testing` given it's the local-only test image?

2021-01-18 00:08 UTC, radicand commented on setup.sh
> +  -i IMAGE_NAME     The name of the docker-mailserver image
Shouldn't we still indicate the default value?

2021-01-18 00:08 UTC, radicand commented on Makefile
> +NAME    ?= mailserver-testing:local
Should we tag this as `ci` for consistency?

2021-01-18 08:46 UTC, aendeavor commented on .github/workflows/default_on_push.yml
> +          tags: ${{ secrets.DOCKER_REPOSITORY }}:ci
You're right. Will be fixed.

2021-01-18 08:48 UTC, aendeavor commented on setup.sh
> +  -i IMAGE_NAME     The name of the docker-mailserver image
Good point. Since we are now always using the "Fully Qualified Repository Name" with docker.io, I got rid of that. I will make sure the default value is displayed again:)

2021-01-18 08:49 UTC, aendeavor commented on Makefile
> +NAME    ?= mailserver-testing:local
I wanted to explicitly make sure to differentiate here, but the more I thinkabout it, the more you're right. I will change that.

2021-01-18 09:33 UTC, aendeavor commented
I have adjusted the PR with the changes requested :)

PS: Please don't mind my edit of the `.editorconfig` file. I just wanted to get it in-line with the other configuration files. A bit of perfectionism :D

2021-01-18 18:51 UTC, radicand approved these changes
LGTM

2021-01-18 19:12 UTC, aendeavor commented
I will merge this when a751b5018f132db83cf3ebc84dba3222327a6361 had completed its tests :D

2021-01-18 19:51 UTC, merged